// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package wago

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type Medium struct {
	ID        int64
	MessageID int64
	MediaUrl  string
	MediaType string
	MediaSize int64
}

type Message struct {
	ID             int64
	ConversationID int64
	Sender         string
	Recipient      string
	Content        pgtype.Text
	MessageType    string
	Timestamp      pgtype.Timestamp
}
